---
title: "EDA_LS_FA"
author: "Cass Lee"
date: "2025-09-02"
output: pdf_document
---

## Preliminary Set Up

```{r import libraries}
# import useful libraries
library(tidyverse)
library(mosaic)
library(ggformula)
library(dplyr)
library(lme4)
```

```{r import data}
# set import file path
path <- '~/Desktop/ENVR356/LS_FA/full_data.csv'
# import full data set
all_data <- read_csv(file = path)
```

## EDA and Data Wrangling

```{r problems}
# address initial problems when loading csv
# image links trying to translate to logical
# remove the image column
data <- select(all_data, -Images)
glimpse(data)
```

```{r wrangling}
# select relevant cols
data1 <- select(data, `trap nid`, `trap type`, status, `initial bait`, rebaited, `bait type`, `Bait details`, strikes, `species caught`)
# rename columns to work better for analysis
colnames(data1) <- c("TrapID", "TrapType", "Status", "InitialBait", 
                        "Rebaited", "BaitType", "BaitDetails", 
                        "Strikes", "SpeciesCaught")
```

# TODO: should probably just save this stuff to a csv rather than doing it in my nice document


