---
title: "LS FA EDA"
author: "Cass Lee"
date: "2025-07-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

! For best results, run these code chunks sequentially in RStudio rather than creating a knitted document.

## Preliminary Set Up

```{r import libraries}
# import useful libraries
library(tidyverse)
library(mosaic)
library(ggformula)
library(dplyr)
library(lme4)
```

```{r import data}
# set import file path
path <- '~/Desktop/ENVR356/LS_FA/full_data.csv'
# import full data set
all_data <- read_csv(file = path)
```

## EDA and Data Wrangling

```{r problems}
# address initial problems when loading csv
# image links trying to translate to logical
# remove the image column
data <- select(all_data, -Images)
glimpse(data)
```

```{r EDA}
# EDA
inspect(data)
```

```{r wrangling}
# select relevant cols
data1 <- select(data, `trap nid`, `trap type`, nid, status, `initial bait`, rebaited, `bait type`, `Bait details`, strikes, `species caught`, notes)
# rename columns to work better for analysis
colnames(data1) <- c("TrapID", "TrapType", "EntryID", "Status", "InitialBait", 
                        "Rebaited", "BaitType", "BaitDetails", 
                        "Strikes", "SpeciesCaught", "Notes")
glimpse(data1)
# make sure data looks good
  # TODO vaguely weird, maybe come back to this
inspect(data1)
```

```{r EDA}
# Check for zero or near zero variance variables
caret::nearZeroVar(data1, saveMetrics = TRUE) |>
  tibble::rownames_to_column() |>
  filter(nzv)
  # no nzv

# TODO missingness
```

```{r}
tally(~BaitType, data=data1)
inspect(data1)
# 426 total combos and singles
```

```{r}
# see how many entries don't contain commas, filter
single_bait <- subset(data1, !grepl(",", BaitType))
tally(~BaitType, data=single_bait)
inspect(single_bait)
# 30 single bait types (including none and other)

# 695 mayo, 5059 peanut butter
```

```{r}
# filter to just single pb and mayo
mayo_pb_bait <- subset(single_bait, grepl("MAYO", toupper(BaitType)) | grepl("PEANUT BUTTER", toupper(BaitType)))
tally(~BaitType, data=mayo_pb_bait)
tally(~SpeciesCaught, data=mayo_pb_bait)
inspect(mayo_pb_bait)

mayo_pb_catch <- subset(mayo_pb_bait, grepl("RAT", toupper(SpeciesCaught)))
tally(~BaitType, data=mayo_pb_catch)
tally(~SpeciesCaught, data=mayo_pb_catch)
tally(~TrapType, data=mayo_pb_catch)
tally(~BaitDetails, data=mayo_pb_catch)
inspect(mayo_pb_catch)
# 55 mayo, 386 pb caught rats
# 1 specifically Kiore, 10 specifically Norway, 101 specifically ship, 329 misc rats
```

```{r}
# filter by entries that include mayo
includes_bait <- subset(data1, grepl("MAYO", toupper(BaitType)))
tally(~BaitType, data=includes_bait)
inspect(includes_bait)
tally(~BaitDetails, data=includes_bait)
```

```{r}
other_bait <- subset(data1, BaitType == "Other (please specify)")
inspect(other_bait)
tally(~BaitDetails, data=other_bait)
```

```{r}
tally(~SpeciesCaught, data=data1)
bycatch <- mutate(data1, Notes = all_data$notes) |>
  subset(SpeciesCaught == "Other" | SpeciesCaught == "Unspecified")
inspect(bycatch)
tally(~Notes, data=bycatch)
```

```{r select data}
# filter to just single kill traps that have mayo or pb as bait
analysis_data <- subset(data1, grepl("MAYO", toupper(BaitType)) | grepl("PEANUT BUTTER", toupper(BaitType))) |>
  subset(!(grepl("AT220", TrapType) | grepl("Sentinel", TrapType) | grepl("Supervisor Max", TrapType)))

# how to distinguish single kill traps
tally(~TrapType, data=analysis_data)
  # all types are specified, may need to ask about which ones are self resetting
  # single: cage trap, D-Rat, DOC 200, DOC 250, leg hold trap, rat trap, SA cat, trapinator
    # cage trap, leg hold trap is live capture
    # rat trap resetting type isn't specified but we can probably pretty safely assume it's single trap per set
  # self-resetting: AT220, sentinel, supervisor max
    # sentinel, supervisor max assumed to not be by looking up quickly but actually recorded as having multiple strikes sometimes
# sentinel trap is specifically for possums, supposed to stop rats from getting bait
```

```{r}
glimpse(analysis_data)
inspect(analysis_data)
# how many traps are there
length(unique(analysis_data$TrapID))
# rebaited
caret::nearZeroVar(analysis_data, saveMetrics = TRUE) |>
  tibble::rownames_to_column() |>
  filter(nzv)
  # vast majority are rebaited
analysis_data |> subset(grepl("No", Rebaited))
  # the two entries that are listed as not rebaited are weird because they do have a different bait type listed than the initial bait
# strike visualization - how many strikes are there, how many strikes are against rats
tally(~SpeciesCaught, data=analysis_data)
  # vast majority are none but then mouse dominates, then rat
```

```{r}
# bait visualization - bait types and combos
tally(~BaitType, data=analysis_data)
# make table of all trap entries and associated baits
unique_bait_viz <- data.frame(EntryID = numeric(), Bait = character())

for (i in rownames(analysis_data)){ # seq(1,10)){ 
  baitvector <- pull(analysis_data[i,],"BaitType") |>
    strsplit(", ")
  for (bait in baitvector){
    unique_bait_viz <- unique_bait_viz |> rows_insert(data.frame(EntryID = analysis_data[i,"EntryID"], Bait = bait))
  }
}
# count number of bait combos
counts <- unique_bait_viz |> group_by(EntryID) |> summarize(BaitsPerEntry = n())
tally(~BaitsPerEntry, data=counts)
# get list of unique baits
unique(unique_bait_viz$Bait)
# count number of times each other bait is associated with mayo vs peanut butter

#counts <- counts |> mutate(
#  eid = analysis_data[analysis_data$EntryID == counts$EntryID,],
#  PB = analysis_data[analysis_data$EntryID == counts$EntryID,"BaitType"]),
#  Mayo = grepl("Mayo", analysis_data[analysis_data$EntryID == counts$EntryID,"BaitType"]))
#subset(unique_bait_viz,grepl("Mayo", Bait))
#tally(~PB, data=counts)
#tally(~Mayo, data=counts)
bait_viz <- analysis_data |> mutate(PB = grepl("Peanut butter", BaitType), Mayo = grepl("Mayo", BaitType))
tally(~PB, data=bait_viz)
tally(~Mayo, data=bait_viz)

unique_bait_viz <- unique_bait_viz |> 
  group_by(EntryID) |> 
  mutate(
    PB = pull(bait_viz[bait_viz$EntryID == EntryID,"PB"]),
    Mayo = pull(bait_viz[bait_viz$EntryID == EntryID,"Mayo"])) |> 
  ungroup()
  
#tally(~PB,data=unique_bait_viz_test)

bait_combos <- 
  unique_bait_viz |> subset(PB == TRUE) |> group_by(Bait) |> summarize(PB = n()) |> 
  full_join(
  unique_bait_viz |> subset(Mayo == TRUE) |> group_by(Bait) |> summarize(Mayo = n()))
bait_combos[is.na(bait_combos)] <- 0
bait_combos

write.csv(bait_viz,"~/Desktop/ENVR356/LS_FA/bait_vizualization2.csv", row.names = FALSE)

write.csv(bait_combos,"~/Desktop/ENVR356/LS_FA/bait_combos2.csv", row.names = FALSE)
```

```{r}
# number of each animal killed with each bait type (in combo with mayo and pb)
animal_per_bait_pb <- unique_bait_viz |> subset(PB == TRUE) |>
  inner_join(
    bait_viz) |>
  select(EntryID, Bait, SpeciesCaught)

tally(~Bait, data=animal_per_bait_pb)
tally(~SpeciesCaught, data=animal_per_bait_pb)
```
```{r}
analysis_data2 <- analysis_data |> 
  mutate(BaitType = case_when(grepl("Other", BaitType) ~ paste(BaitType,BaitDetails,sep=", "),
                              TRUE ~ BaitType))

tally(~BaitType, data=analysis_data2)

unique_bait_viz2 <- data.frame(EntryID = numeric(), Bait = character())
for (i in rownames(analysis_data2)){ # seq(1,10)){ 
  baitvector2 <- pull(analysis_data2[i,],"BaitType") |>
    strsplit(", ")
  for (bait in baitvector2){
    unique_bait_viz2 <- unique_bait_viz2 |> rows_insert(data.frame(EntryID = analysis_data2[i,"EntryID"], Bait = bait))
  }
}

bait_viz2 <- analysis_data2 |> mutate(PB = grepl("Peanut butter", BaitType), Mayo = grepl("Mayo", BaitType))

unique_bait_viz2 <- unique_bait_viz2 |> 
  group_by(EntryID) |> 
  mutate(
    PB = pull(bait_viz2[bait_viz2$EntryID == EntryID,"PB"]),
    Mayo = pull(bait_viz2[bait_viz2$EntryID == EntryID,"Mayo"])) |> 
  ungroup()

animal_per_bait_pb2 <- unique_bait_viz2 |> subset(PB == TRUE) |>
  inner_join(
    bait_viz2) |>
  select(EntryID, Bait, SpeciesCaught)

animal_per_bait_pb_combined2 <- subset(animal_per_bait_pb2, Bait != "Peanut butter") |>
  mutate(Bait = as.factor(Bait), SpeciesCaught = as.factor(SpeciesCaught)) |>
  mutate(SpeciesCaught = fct_collapse(SpeciesCaught,
                                    Bird = c("Magpie", "Other"),
                                    Rat = c("Rat - Kiore","Rat - Norway","Rat - Ship"),
                                    Mustelid = c("Ferret","Stoat","Weasel"),
                                    'Other Mammal' = c("Cat","Hedgehog","Possum","Rabbit")) |>
           fct_infreq() |> fct_rev(),
         Bait = fct_collapse(Bait,
                           Meat = c("Dehydrated Rabbit","Fresh meat","Lure-it Salmon Spray","Salmon","Salted Possum","Fresh Possum","Salmon oil","Salted Rabbit","Fresh Rabbit","Salted meat","Good Nature Meat Lovers"),
                           'Non-food lure' = c("Golf ball","Terracotta Lures","Fake Egg","Lure"),
                           'Dog food' = c("Deep Fried Dog Roll")) |>
           fct_recode("GN chocolate" = "Good Nature Chocolate",
                      "Possum dough" = "Possum Dough")
         # |> fct_lump_min(10) |> fct_infreq()
         )
```

```{r}
counts2 <- unique_bait_viz2 |> group_by(EntryID) |> summarize(BaitsPerEntry = n()) |> inner_join(unique_bait_viz2)
tally(~BaitsPerEntry,data=counts2)

gf_boxplot(BaitsPerEntry~"Peanut butter", data=subset(counts2,PB==TRUE), fill="darkorange") |> gf_boxplot(BaitsPerEntry~"Mayo", data=subset(counts2,Mayo==TRUE), fill = "skyblue") |>
  gf_labs(x="",y="Number of baits per rebaiting") +
  theme_classic() + 
  theme(axis.text.x=element_text(size=10,colour="black"),
        axis.text.y=element_text(colour="black"))
```

```{r}
mosaicplot(Bait~SpeciesCaught, 
           data=subset(animal_per_bait_pb_combined2, Bait!="Peanut butter"),
           #srt = 45,
           las=2,
           color = c("red", "orange","gold", "green", "blue", "purple"),
           main = "",
           xlab = "Bait",
           ylab = "Caught Species")
```

```{r}
# look at the "other"s
animal_per_bait <- unique_bait_viz |>
  inner_join(
    bait_viz) |>
  select(EntryID, Bait, SpeciesCaught, Notes)

analysis_data |> subset(grepl("Other", BaitType)) |> select(EntryID, BaitType, BaitDetails, Notes) |> 
  mutate(BaitType = BaitDetails)

# append columns to the unique bait viz table for 
# ex. if the bait details column says dog, append a column for the entry id saying dog roll
#TODO ask to see if "dog meat" being dog roll is a fair assumption or if this is literally the meat of a dog

# lover, salmon, butter, mouse

# also canned dog food

# some NAs with no notes...

subset(animal_per_bait, SpeciesCaught == "Other")
# it's a chaffinch
```

```{r}
single_bait_analysis <- subset(analysis_data, !grepl(",", BaitType))
tally(~BaitType, data=single_bait_analysis)
```

```{r}
animal_per_bait_pb_combined <- subset(animal_per_bait_pb, Bait != "Peanut butter") |>
  mutate(Bait = as.factor(Bait), SpeciesCaught = as.factor(SpeciesCaught)) |>
  mutate(SpeciesCaught = fct_collapse(SpeciesCaught,
                                    Bird = c("Magpie", "Other"),
                                    Rat = c("Rat - Kiore","Rat - Norway","Rat - Ship"),
                                    Mustelid = c("Ferret","Stoat","Weasel"),
                                    'Other Mammal' = c("Cat","Hedgehog","Possum","Rabbit")) |>
           fct_infreq() |> fct_rev(),
         Bait = fct_collapse(Bait,
                           Meat = c("Dehydrated Rabbit","Fresh meat","Lure-it Salmon Spray","Salmon","Salted Possum","Fresh Possum","Salmon oil","Salted Rabbit","Fresh Rabbit","Salted meat","Good Nature Meat Lovers"),
                           'Non-food lure' = c("Golf ball","Terracotta Lures","Fake Egg","Lure")) |>
           fct_recode("GN chocolate" = "Good Nature Chocolate",
                      "Dog roll" = "Deep Fried Dog Roll",
                      "Possum dough" = "Possum Dough")
         |> fct_lump_min(10) |> fct_infreq()
         )

# what is cats goodnature stoat lure
# going to have to look at the notes for other TT
```

```{r}
mosaicplot(Bait~SpeciesCaught, 
           data=subset(animal_per_bait_pb_combined, Bait!="Peanut butter"),
           #srt = 45,
           las=2,
           color = c("red", "orange","gold", "green", "blue", "purple"),
           main = "",
           xlab = "Bait",
           ylab = "Caught Species") + 
  theme(axis.text.x = element_text(angle = 45,
                                   vjust = 0.5,
                                   hjust = 0.5))
```

```{r}
library(ggmosaic)

ggplot(data=subset(animal_per_bait_pb_combined, Bait!="Peanut butter")) + 
  geom_mosaic(aes(x=product(SpeciesCaught,Bait),fill=Bait),
           #srt = 45,
           #las=2,
           color = c("red", "orange","gold", "green", "blue", "purple"),
           main = "",
           xlab = "Bait",
           ylab = "Caught Species") + 
  theme(axis.text.x = element_text(angle = 45,
                                   vjust = 0.5,
                                   hjust = 0.5))
```

```{r}
# table that looks like pb mayo and then columns for each
# also visualize number of baits in combos 
# seems best way is making a new table that includes each trap entry and separates the baits using commas to make entries in the table, then can go through and tally


# make new table for bait info
bait_viz <- select(analysis_data, BaitType) |>
  mutate(baitvec = as.vector(strsplit(BaitType, ", "))) |>
# make new column for each trap entry's # of baits 
  mutate(BaitNum = length(baitvec)) |> # count number of commas
# make new column for trap entry's pb or mayo
  mutate(PB = "Peanut butter" %in% baitvec) # is pb in bait type (grepl)

#cycle through ans collect all unique bait values
baits <- c()
for (i in rownames(analysis_data)){
  baits <- c(baits,i$baitvec)
}
baits <- unique(baits)

# for each bait value, count how 
baits <- c()
for (i in rownames(analysis_data)){
  baits <- c(baits,i$baitvec)
}
baits <- unique(baits)

# get the baits as separate strings
baits <- strsplit("a, b, c", ", ")
# get length and put in trap record table
# for each bait
  # add new entry if necessary
  # figure out whether associated with pb or mayo
  # increment pb or mayo combo count


bait_viz2 <- 

unique_bait_viz <- data.frame(EntryID = numeric(), Bait = character())
  # set up a table of nid and bait from the individual bait vectors
for (i in rownames(analysis_data)){ # seq(1,10)){ 
  baitvector <- pull(analysis_data[i,],"BaitType") |>
    strsplit(", ")
  for (bait in baitvector){
    unique_bait_viz <- unique_bait_viz |> rows_insert(data.frame(EntryID = analysis_data[i,"EntryID"], Bait = bait))
  }
}

# as.vector(analysis_data[421,"BaitType"])
analysis_data[421,"BaitType"]

pull(analysis_data[421,],"BaitType")
strsplit(pull(analysis_data[421,],"BaitType"),", ")

baits <- unique(baits)
```

```{r}
tally(~Bait,subset(unique_bait_viz2, Mayo==TRUE))
  # most common is mayo and peanut butter with 63/138
only_2 <- subset(bait_viz2,str_count(BaitType,",")==1)
  # either this or the counts is wrong
tally(~BaitType, data=subset(only_2,Mayo==TRUE))
  # with the jank probably broken counting, 10 mayo and pb, 19 + 8 mayo and possum dough
tally(~BaitType, data=subset(only_2,PB==TRUE))
  # oddly good amount of just PB and dog roll
tally(~Bait,unique_bait_viz2)
tally(~BaitsPerEntry,data=counts2)
# just mayo
tally(~BaitType, data=subset(bait_viz2,!grepl(",",BaitType)))
  # 13 just mayo
```
```{r}
# possible analysis plan - mayo+pb (63) vs just pb (4406)
```


```{r}
# first try at linear mixed model
#TODO may need to make the variables into factors
SetSprung <- 
HabitatType
#SamplingPeriod <- 
#Time
  # time of day can't be determined I think, maybe do season and nested within it vague date
lmer(SetSprung ~ BaitType + (1 | Date))#(1 | Period) + (1 | Time))
  # can maybe do date as a main effect as well bc continuous and then get effect of seasons
  # maybe need to do PB and Mayo variables separately and also include one perhaps for dog roll or whatever the second thing is

# days since set rather than time of night - can include as a main effect
# random effect really matters for period;p

  # doing just the 1 | var - allows the intercept to vary for the different groups, something we would like to account for but don't really care out
  # (response | var) is weird
  # TODO if set sprung then need glmer to do logistic regression (try with binomial family #or bernoulli)
  # cat vars on yes mayo or yes pb

  # does have the assumption of normality for the linear one

#lmer(SetSprung ~ BaitType + (BaitType | HabitatType) + (BaitType | Period) + (BaitType | Time))
  # response: set:sprung
  # fixed effect: bait type
  # random effect: habitat type, sampling period, time of day
    # a | b means different levels of a have different effects based on the value of b
# TODO habitat type is prob too much work so can prob chuck
#We evaluated whether the ratio of set to sprung traps can be predicted by the fixed effect of bait type and the random effects of habitat type, sampling period, and time of day using a linear mixed effects model.

# TODO look into nlmer for the things with main variables as categorics??
```
