---
title: "MessyEDA_Allendale_FA"
author: "Cass Lee"
date: "2025-09-14"
output: pdf_document
---


! For best results, run these code chunks sequentially in RStudio rather than creating a knitted document.

## Preliminary Set Up

```{r import libraries}
# import useful libraries
library(tidyverse)
library(mosaic)
library(ggformula)
library(dplyr)
library(lme4)
```

```{r import data}
# set import file path
path_a <- '~/Desktop/ENVR356/LS_FA/allendale_data.csv'
# import full data set
all_data_a <- read_csv(file = path_a)
```
```{r}
glimpse(all_data_a)
```

```{r wrangling}
# select relevant cols
data1_a <- select(all_data_a, `trap nid`, `trap type`, nid, status, `initial bait`, rebaited, `bait type`, `Bait details`, strikes, `species caught`, notes)
# rename columns to work better for analysis
colnames(data1_a) <- c("TrapID", "TrapType", "EntryID", "Status", "InitialBait", 
                        "Rebaited", "BaitType", "BaitDetails", 
                        "Strikes", "SpeciesCaught", "Notes")
glimpse(data1_a)
# make sure data looks good
  # TODO vaguely weird, maybe come back to this
inspect(data1_a)
```
```{r wrangling 2}
# select relevant cols for the new type of analysis i'm considering as of 16/10
data2_a <- select(all_data_a, `trap nid`, `trap type`, nid, date, status, `bait type`, `Bait details`, strikes, `species caught`, notes)
# rename columns to work better for analysis
colnames(data2_a) <- c("TrapID", "TrapType", "EntryID", "Date", "Status","BaitType", "BaitDetails", 
                        "Strikes", "SpeciesCaught", "Notes")
glimpse(data2_a)
# make sure data looks good
```

```{r}
# EDA for trap type, bait type
tally(~TrapType, data=data1_a)
tally(~BaitType, data=data1_a)
```

```{r}
# single kill
# filter to just single kill traps that have mayo or pb as bait
analysis_data_a <- subset(data1_a, grepl("MAYO", toupper(BaitType)) | grepl("PEANUT BUTTER", toupper(BaitType))) |>
  subset(!(grepl("AT220", TrapType) | grepl("Sentinel", TrapType) | grepl("Supervisor Max", TrapType)))

# how to distinguish single kill traps
  # 27 unspecified
  # single: cage trap, D-Rat, DOC 200, DOC 250, leg hold trap, rat trap, SA cat, Tāwhiti - Smart Cage, trapinator
    # cage trap, leg hold trap, Tāwhiti - Smart Cage is live capture
    # rat trap resetting type isn't specified but we can probably pretty safely assume it's single trap per set
  # self-resetting: AT220, sentinel, supervisor max
    # sentinel, supervisor max assumed to not be by looking up quickly but actually recorded as having multiple strikes sometimes
# sentinel trap is specifically for possums, supposed to stop rats from getting bait
```

```{r}
tally(~BaitType, data=analysis_data_a)
```

```{r}
# look at the self-resetting trap data to see if it can be made to compare to single kill
resetting_a <- subset(data2_a, grepl("MAYO", toupper(BaitType)) | grepl("PEANUT BUTTER", toupper(BaitType))) |>
  subset(grepl("AT220", TrapType) | grepl("Sentinel", TrapType) | grepl("Supervisor Max", TrapType))
tally(~BaitType, data=resetting_a)
resetting_a[resetting_a$BaitType=="Mayo",]
```

```{r}
# servicing interval for self-resetting traps
  # scatter plot with line drawn through
  # x axis is time, strikes is y axis
  # entryid is series
gf_line(Strikes~Date, color=~as.factor(TrapID),data=resetting_a)
```
